namespace WorldBuilder.Shared.Modules.Landscape.Models
{
    /// <summary>
    /// Fully flattened map of a Landblock objects.
    /// Generated by traversing the active layer stack and compositing base Data with Layer overrides.
    /// </summary>
    public class MergedLandblock
    {
        /// <summary>
        /// The computed visible final buildings inside this Landblock.
        /// </summary>
        public List<BuildingObject> Buildings { get; init; } = [];

        /// <summary>
        /// The computed visible final static objects inside this Landblock.
        /// </summary>
        public List<StaticObject> StaticObjects { get; init; } = [];
    }
}
