using WorldBuilder.Modules.DatBrowser.ViewModels;

namespace WorldBuilder.Modules.DatBrowser.Factories {
    public interface IDatBrowserViewModelFactory {
        IterationBrowserViewModel CreateIterationBrowser();
        GfxObjBrowserViewModel CreateGfxObjBrowser();
        SetupBrowserViewModel CreateSetupBrowser();
        AnimationBrowserViewModel CreateAnimationBrowser();
        PaletteBrowserViewModel CreatePaletteBrowser();
        SurfaceTextureBrowserViewModel CreateSurfaceTextureBrowser();
        RenderSurfaceBrowserViewModel CreateRenderSurfaceBrowser();
        SurfaceBrowserViewModel CreateSurfaceBrowser();
        MotionTableBrowserViewModel CreateMotionTableBrowser();
        WaveBrowserViewModel CreateWaveBrowser();
        EnvironmentBrowserViewModel CreateEnvironmentBrowser();
        ChatPoseTableBrowserViewModel CreateChatPoseTableBrowser();
        ObjectHierarchyBrowserViewModel CreateObjectHierarchyBrowser();
        BadDataTableBrowserViewModel CreateBadDataTableBrowser();
        TabooTableBrowserViewModel CreateTabooTableBrowser();
        NameFilterTableBrowserViewModel CreateNameFilterTableBrowser();
        PalSetBrowserViewModel CreatePalSetBrowser();
        ClothingTableBrowserViewModel CreateClothingTableBrowser();
        GfxObjDegradeInfoBrowserViewModel CreateGfxObjDegradeInfoBrowser();
        SceneBrowserViewModel CreateSceneBrowser();
        RegionBrowserViewModel CreateRegionBrowser();
        MasterInputMapBrowserViewModel CreateMasterInputMapBrowser();
        RenderTextureBrowserViewModel CreateRenderTextureBrowser();
        RenderMaterialBrowserViewModel CreateRenderMaterialBrowser();
        MaterialModifierBrowserViewModel CreateMaterialModifierBrowser();
        MaterialInstanceBrowserViewModel CreateMaterialInstanceBrowser();
        SoundTableBrowserViewModel CreateSoundTableBrowser();
        EnumMapperBrowserViewModel CreateEnumMapperBrowser();
        EnumIDMapBrowserViewModel CreateEnumIDMapBrowser();
        ActionMapBrowserViewModel CreateActionMapBrowser();
        DualEnumIDMapBrowserViewModel CreateDualEnumIDMapBrowser();
        LanguageStringBrowserViewModel CreateLanguageStringBrowser();
        ParticleEmitterBrowserViewModel CreateParticleEmitterBrowser();
        PhysicsScriptBrowserViewModel CreatePhysicsScriptBrowser();
        PhysicsScriptTableBrowserViewModel CreatePhysicsScriptTableBrowser();
        MasterPropertyBrowserViewModel CreateMasterPropertyBrowser();
        FontBrowserViewModel CreateFontBrowser();
        DBPropertiesBrowserViewModel CreateDBPropertiesBrowser();
        CharGenBrowserViewModel CreateCharGenBrowser();
        VitalTableBrowserViewModel CreateVitalTableBrowser();
        SkillTableBrowserViewModel CreateSkillTableBrowser();
        SpellTableBrowserViewModel CreateSpellTableBrowser();
        SpellComponentTableBrowserViewModel CreateSpellComponentTableBrowser();
        ExperienceTableBrowserViewModel CreateExperienceTableBrowser();
        QualityFilterBrowserViewModel CreateQualityFilterBrowser();
        CombatTableBrowserViewModel CreateCombatTableBrowser();
        ContractTableBrowserViewModel CreateContractTableBrowser();
        LandBlockBrowserViewModel CreateLandBlockBrowser();
        LandBlockInfoBrowserViewModel CreateLandBlockInfoBrowser();
        EnvCellBrowserViewModel CreateEnvCellBrowser();
        LayoutDescBrowserViewModel CreateLayoutDescBrowser();
        StringTableBrowserViewModel CreateStringTableBrowser();
        LanguageInfoBrowserViewModel CreateLanguageInfoBrowser();
    }
}
